In [1]:
import math
import pandas_datareader as web
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import yfinance as yf
plt.style.use('fivethirtyeight')

In [6]:
apple_quote = yf.download('AAPL', start='2012-01-01', end='2023-07-15')

new_df = apple_quote.filter(['Close'])

new_df

last_60_days = new_df[-60:].values

last_60_days

[*********************100%***********************]  1 of 1 completed


array([[167.63000488],
       [166.6499939 ],
       [165.02000427],
       [165.33000183],
       [163.77000427],
       [163.75999451],
       [168.41000366],
       [169.67999268],
       [169.58999634],
       [168.53999329],
       [167.44999695],
       [165.78999329],
       [173.57000732],
       [173.5       ],
       [171.77000427],
       [173.55999756],
       [173.75      ],
       [172.57000732],
       [172.07000732],
       [172.07000732],
       [172.69000244],
       [175.05000305],
       [175.16000366],
       [174.19999695],
       [171.55999756],
       [171.83999634],
       [172.99000549],
       [175.42999268],
       [177.30000305],
       [177.25      ],
       [180.08999634],
       [180.94999695],
       [179.58000183],
       [179.21000671],
       [177.82000732],
       [180.57000732],
       [180.96000671],
       [183.78999329],
       [183.30999756],
       [183.94999695],
       [186.00999451],
       [184.91999817],
       [185.00999451],
       [183

In [50]:
apple_quote

Open        High         Low       Close   Adj Close   
Date                                                                     
2012-01-03   14.621429   14.732143   14.607143   14.686786   12.482924  \
2012-01-04   14.642857   14.810000   14.617143   14.765714   12.550010   
2012-01-05   14.819643   14.948214   14.738214   14.929643   12.689340   
2012-01-06   14.991786   15.098214   14.972143   15.085714   12.821991   
2012-01-09   15.196429   15.276786   15.048214   15.061786   12.801656   
...                ...         ...         ...         ...         ...   
2023-07-10  189.259995  189.990005  187.039993  188.610001  188.610001   
2023-07-11  189.160004  189.300003  186.600006  188.080002  188.080002   
2023-07-12  189.679993  191.699997  188.470001  189.770004  189.770004   
2023-07-13  190.500000  191.190002  189.779999  190.539993  190.539993   
2023-07-14  190.229996  191.179993  189.630005  190.690002  190.690002   

               Volume  
Date                   
2012-01-03  302220800  
2012-01-04  260022000  
2012-01-05  271269600  
2012-01-06  318292800  
2012-01-09  394024400  
...               ...  
2023-07-10   59922200  
2023-07-11   46638100  
2023-07-12   60750200  
2023-07-13   41342300  
2023-07-14   41573900  

[2901 rows x 6 columns]

In [42]:
scaler = MinMaxScaler(feature_range=(0,1))
last_60_days_scaled = scaler.fit_transform(last_60_days)

last_60_days_scaled

# for i in last_60_days_scaled:
#     print(i)



array([[1.28103592e-01],
       [9.56636461e-02],
       [4.17083577e-02],
       [5.19697774e-02],
       [3.31339404e-04],
       [0.00000000e+00],
       [1.53922811e-01],
       [1.95961498e-01],
       [1.92982474e-01],
       [1.58225677e-01],
       [1.22145039e-01],
       [6.71962373e-02],
       [3.24727264e-01],
       [3.22409908e-01],
       [2.65144256e-01],
       [3.24395924e-01],
       [3.30685312e-01],
       [2.91625649e-01],
       [2.75074842e-01],
       [2.75074842e-01],
       [2.95597681e-01],
       [3.73717512e-01],
       [3.77358710e-01],
       [3.45580937e-01],
       [2.58192695e-01],
       [2.67461107e-01],
       [3.05528267e-01],
       [3.86295782e-01],
       [4.48196145e-01],
       [4.46540963e-01],
       [5.40549427e-01],
       [5.69016836e-01],
       [5.23667786e-01],
       [5.11420350e-01],
       [4.65409126e-01],
       [5.56438566e-01],
       [5.69348176e-01],
       [6.63025300e-01],
       [6.47136667e-01],
       [6.68321680e-01],


In [46]:
X_test = []

X_test.append(last_60_days_scaled)

X_test

X_test = np.array(X_test)

X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

X_test

array([[[1.28103592e-01],
        [9.56636461e-02],
        [4.17083577e-02],
        [5.19697774e-02],
        [3.31339404e-04],
        [0.00000000e+00],
        [1.53922811e-01],
        [1.95961498e-01],
        [1.92982474e-01],
        [1.58225677e-01],
        [1.22145039e-01],
        [6.71962373e-02],
        [3.24727264e-01],
        [3.22409908e-01],
        [2.65144256e-01],
        [3.24395924e-01],
        [3.30685312e-01],
        [2.91625649e-01],
        [2.75074842e-01],
        [2.75074842e-01],
        [2.95597681e-01],
        [3.73717512e-01],
        [3.77358710e-01],
        [3.45580937e-01],
        [2.58192695e-01],
        [2.67461107e-01],
        [3.05528267e-01],
        [3.86295782e-01],
        [4.48196145e-01],
        [4.46540963e-01],
        [5.40549427e-01],
        [5.69016836e-01],
        [5.23667786e-01],
        [5.11420350e-01],
        [4.65409126e-01],
        [5.56438566e-01],
        [5.69348176e-01],
        [6.63025300e-01],
        [6.4

In [47]:
from tensorflow.keras.models import load_model

model = load_model("trained_lstm_model.h5")

In [48]:
pred_price = model.predict(X_test)

1/1 [==============================] - 1s 630ms/step


In [49]:
pred_price

array([[0.8820032]], dtype=float32)

In [39]:
pred_price = scaler.inverse_transform(pred_price)

print(pred_price)

[[178883.31]]


In [40]:
pred_price = model.predict(X_test)

pred_price = scaler.inverse_transform(pred_price)

print(pred_price)



1/1 [==============================] - 0s 21ms/step
[[190.40532]]


In [41]:
apple_quote2 = yf.download('AAPL', start='2023-07-15', end='2023-07-18')

apple_quote2

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close   Adj Close   
Date                                                                     
2023-07-17  191.899994  194.320007  191.809998  193.990005  193.990005  \

              Volume  
Date                  
2023-07-17  50520200